# Generated by Django 6.0 on 2025-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.TextField()),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('patient_phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('recent_report', models.FileField(blank=True, null=True, upload_to='appointment_reports')),
                ('reson', models.TextField()),
            ],
        ),
    ]
